<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pas</string>
	</array>
	<key>name</key>
	<string>PapyrusF4 Assembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#literalsAndComments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#info</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#userFlagsRef</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#objectTable</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>boolean</key>
		<dict>
			<key>match</key>
			<string>(?i)\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language.bool.papyrusf4-assembly</string>
		</dict>
		<key>numeric</key>
		<dict>
			<key>match</key>
			<string>\b[\d.]+\b</string>
			<key>name</key>
			<string>constant.numeric.papyrusf4-assembly</string>
		</dict>
		<key>noneLiteral</key>
		<dict>
			<key>match</key>
			<string>(?i)\b(none)\b</string>
			<key>name</key>
			<string>constant.language.none.papyrusf4-assembly</string>
		</dict>
		<key>semicolonComment</key>
		<dict>
			<key>match</key>
			<string>;.*$</string>
			<key>name</key>
			<string>comment.line.semicolon.code.papyrusf4-assembly</string>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.papyrusf4-assembly</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.papyrusf4-assembly</string>
				</dict>
			</array>
		</dict>
		<key>literalsAndComments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#noneLiteral</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#semicolonComment</string>
				</dict>
			</array>
		</dict>
		<key>return</key>
		<dict>
			<key>match</key>
			<string>(?i)^\s*(\.)(return)\s+(\w+)</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.return.papyrusf4-assembly</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.papyrusf4-assembly</string>
				</dict>
			</dict>
		</dict>
		<key>userFlags</key>
		<dict>
			<key>match</key>
			<string>(?i)^\s*(\.)(userflags)\b</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.userflags.papyrusf4-assembly</string>
				</dict>
			</dict>
		</dict>
		<key>docString</key>
		<dict>
			<key>match</key>
			<string>(?i)^\s*(\.)(docstring)\b</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.docstring.papyrusf4-assembly</string>
				</dict>
			</dict>
		</dict>
		<key>autoState</key>
		<dict>
			<key>match</key>
			<string>(?i)^\s*(\.)(autostate)\b(\s+(\w+))?</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.autostate.papyrusf4-assembly</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.state.papyrusf4-assembly</string>
				</dict>
			</dict>
		</dict>
		<key>initialValue</key>
		<dict>
			<key>match</key>
			<string>(?i)^\s*(\.)(initialValue)\b</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.initialvalue.papyrusf4-assembly</string>
				</dict>
			</dict>
		</dict>
		<key>variable</key>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*(\.)(variable)\s+((::\w+)|(\w+))\s+([:#\w\[\]]+)(\s+(const)\b)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.variable.papyrusf4-assembly</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.variable.papyrusf4-assembly</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>storage.type.papyrusf4-assembly</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>keyword.other.modifier.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)^\s*(\.)(endVariable)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.endvariable.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#userFlags</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#docString</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#initialValue</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literalsAndComments</string>
				</dict>
			</array>
		</dict>
		<key>struct</key>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*(\.)(struct)\s+(\w+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.struct.papyrusf4-assembly</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.struct.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)^\s*(\.)(endStruct)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.endstruct.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literalsAndComments</string>
				</dict>
			</array>
		</dict>
		<key>structTable</key>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*(\.)(structTable)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.structtable.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)^\s*(\.)(endStructTable)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.endstructtable.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#struct</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literalsAndComments</string>
				</dict>
			</array>
		</dict>
		<key>variableTable</key>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*(\.)(variableTable)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.variabletable.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)^\s*(\.)(endVariableTable)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.endvariabletable.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literalsAndComments</string>
				</dict>
			</array>
		</dict>
		<key>property</key>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*(\.)(property)\s+(\w+)\s+([:#\w\[\]]+)(\s+(auto)\b)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.property.papyrusf4-assembly</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.property.papyrusf4-assembly</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type.papyrusf4-assembly</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.other.modifier.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)^\s*(\.)(endProperty)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.endproperty.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#userFlags</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#docString</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)^\s*(\.)(autoVar)\s+(::\w+)</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.autovar.papyrusf4-assembly</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.variable.papyrusf4-assembly</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literalsAndComments</string>
				</dict>
			</array>
		</dict>
		<key>propertyTable</key>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*(\.)(propertyTable)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.propertytable.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)^\s*(\.)(endPropertyTable)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.endpropertytable.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#property</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literalsAndComments</string>
				</dict>
			</array>
		</dict>
		<key>propertyGroup</key>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*(\.)(propertyGroup)\b(\s+(\w+))?</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.propertygroup.papyrusf4-assembly</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.propertygroup.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)^\s*(\.)(endPropertyGroup)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.endpropertygroup.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#userFlags</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#docString</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)^\s*(\.)(property)\s+(\w+)</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.property.papyrusf4-assembly</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.property.papyrusf4-assembly</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#literalsAndComments</string>
				</dict>
			</array>
		</dict>
		<key>propertyGroupTable</key>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*(\.)(propertyGroupTable)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.propertygrouptable.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)^\s*(\.)(endPropertyGroupTable)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.endpropertygrouptable.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#propertyGroup</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literalsAndComments</string>
				</dict>
			</array>
		</dict>
		<key>param</key>
		<dict>
			<key>match</key>
			<string>(?i)^\s*(\.)(param)\s+((::\w+)|(\w+))\s+([:#\w\[\]]+)</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.param.papyrusf4-assembly</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.temp.papyrusf4-assembly</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.papyrusf4-assembly</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>storage.type.papyrusf4-assembly</string>
				</dict>
			</dict>
		</dict>
		<key>paramTable</key>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*(\.)(paramTable)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.paramtable.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)^\s*(\.)(endParamTable)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.endparamtable.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#param</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literalsAndComments</string>
				</dict>
			</array>
		</dict>
		<key>local</key>
		<dict>
			<key>match</key>
			<string>(?i)^\s*(\.)(local)\s+((::\w+)|(\w+))\s+([:#\w\[\]]+)</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.local.papyrusf4-assembly</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.other.temp.papyrusf4-assembly</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.other.papyrusf4-assembly</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>storage.type.papyrusf4-assembly</string>
				</dict>
			</dict>
		</dict>
		<key>localTable</key>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*(\.)(localTable)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.localtable.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)^\s*(\.)(endLocalTable)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.endlocaltable.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#local</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literalsAndComments</string>
				</dict>
			</array>
		</dict>
		<key>code</key>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*(\.)(code)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.code.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)^\s*(\.)(endCode)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.endcode.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#literalsAndComments</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i)(::(state|NoneVar|temp\d+)|\bself)\b</string>
							<key>name</key>
							<string>variable.language.code.papyrusf4-assembly</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i)^\s*(NOOP)\b</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.noop.code.papyrusf4-assembly</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i)^\s*(RETURN)\b</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.control.return.code.papyrusf4-assembly</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i)^\s*(CALLMETHOD)\s+(\w+)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.callmethod.code.papyrusf4-assembly</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i)^\s*(CALLSTATIC)\s+(\w+)\s+(\w+)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.callmethod.code.papyrusf4-assembly</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>storage.type.code.papyrusf4-assembly</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i)^\s*(CALLPARENT)\s+(\w+)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.callparent.code.papyrusf4-assembly</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i)^\s*(PROPGET|PROPSET)\b</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.code.papyrusf4-assembly</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i)^\s*(CAST)\b</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.cast.code.papyrusf4-assembly</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i)^\s*(IS)\b</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.is.code.papyrusf4-assembly</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i)^\s*((I|F)ADD|(I|F)SUBTRACT|(I|F)NEGATE|(I|F)MULTIPLY|(I|F)DIVIDE|IMOD)\b</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.arithmetic.code.papyrusf4-assembly</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i)^\s*(COMPAREEQ|COMPAREGT(E)?|COMPARELT(E)?|NOT)\b</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.logical.code.papyrusf4-assembly</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i)^\s*(STRCAT)\b</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.string.code.papyrusf4-assembly</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i)^\s*(ASSIGN)\b</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.assignment.code.papyrusf4-assembly</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i)^\s*(ARRAYCREATE|ARRAYLENGTH|ARRAYGETELEMENT|ARRAYSETELEMENT|ARRAYFINDELEMENT|ARRAYRFINDELEMENT|ARRAYFINDSTRUCT|ARRAYRFINDSTRUCT|ARRAYADDELEMENTS|ARRAYINSERTELEMENT|ARRAYREMOVELASTELEMENT|ARRAYREMOVEELEMENTS|ARRAYCLEARELEMENTS)\b</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.array.code.papyrusf4-assembly</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i)^\s*(STRUCTCREATE|STRUCTGET|STRUCTSET)\b</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.struct.code.papyrusf4-assembly</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i)^\s*(JUMP)\s+(\w+)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.control.jump.code.papyrusf4-assembly</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.label.code.papyrusf4-assembly</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i)^\s*(JUMP(F|T))\s+(\S+)\s+(\w+)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.control.jump.code.papyrusf4-assembly</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.label.code.papyrusf4-assembly</string>
								</dict>
							</dict>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i)^\s*(\w+)(:)</string>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.label.code.papyrusf4-assembly</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.control.label.code.papyrusf4-assembly</string>
								</dict>
							</dict>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>function</key>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*(\.)(function)\s+((::\w+)|(\w+))((\s+\w+)*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.function.papyrusf4-assembly</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.papyrusf4-assembly</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)^\s*(\.)(endFunction)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.endfunction.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#return</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#userFlags</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#docString</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#paramTable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#localTable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literalsAndComments</string>
				</dict>
			</array>
		</dict>
		<key>state</key>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*(\.)(state)\b(\s+(\w+))?</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.state.papyrusf4-assembly</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.state.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)^\s*(\.)(endState)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.endstate.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literalsAndComments</string>
				</dict>
			</array>
		</dict>
		<key>stateTable</key>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*(\.)(stateTable)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.statetable.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)^\s*(\.)(endStateTable)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.endstatetable.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#state</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literalsAndComments</string>
				</dict>
			</array>
		</dict>
		<key>object</key>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*(\.)(object)\s+(\w+)\b(\s+([:\w]+))?(\s+(const)\b)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.object.papyrusf4-assembly</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.object.papyrusf4-assembly</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>storage.type.papyrusf4-assembly</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>keyword.other.modifier.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)^\s*(\.)(endObject)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.endobject.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#userFlags</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#docString</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#autoState</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#structTable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variableTable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#propertyTable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#propertyGroupTable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#stateTable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literalsAndComments</string>
				</dict>
			</array>
		</dict>
		<key>objectTable</key>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*(\.)(objectTable)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.objecttable.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)^\s*(\.)(endObjectTable)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.endobjecttable.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#object</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literalsAndComments</string>
				</dict>
			</array>
		</dict>
		<key>info</key>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*(\.)(info)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.info.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)^\s*(\.)(endInfo)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.endinfo.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)^\s*(\.)(source)\b</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.source.papyrusf4-assembly</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)^\s*(\.)(modifyTime)\b</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.modifytime.papyrusf4-assembly</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)^\s*(\.)(compileTime)\b</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.compiletime.papyrusf4-assembly</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)^\s*(\.)(user)\b</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.user.papyrusf4-assembly</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)^\s*(\.)(computer)\b</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.computer.papyrusf4-assembly</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#literalsAndComments</string>
				</dict>
			</array>
		</dict>
		<key>userFlagsRef</key>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*(\.)(userFlagsRef)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.userflagsref.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)^\s*(\.)(endUserFlagsRef)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.enduserflagsref.papyrusf4-assembly</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)^\s*(\.)(flag)\s+(\w+)\b</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.flag.papyrusf4-assembly</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.flag.papyrusf4-assembly</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>include</key>
					<string>#literalsAndComments</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.papyrusf4-assembly</string>
	<key>uuid</key>
	<string>8DEE1F83-C5B5-4C7C-93A2-D35F26BAA32D</string>
</dict>
</plist>
